improve

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -21,7 +21,6 @@ jobs:
     if: ${{ github.event.pull_request.draft == false }}
     outputs:
       skip-tests: ${{ contains(github.event.pull_request.labels.*.name, 'skip-bittensor-tests') }}
-      run-cli-tests: ${{ contains(github.event.pull_request.labels.*.name, 'run-bittensor-cli-tests') }}
       run-sdk-tests: ${{ contains(github.event.pull_request.labels.*.name, 'run-bittensor-sdk-tests') }}
     steps:
       - name: Check out repository
@@ -39,7 +38,7 @@ jobs:
       - name: Install dependencies
         run: |
           sudo apt-get update &&
-          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler
+          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler jq
 
       - name: Install Rust stable
         uses: actions-rs/toolchain@v1.0.6
@@ -54,79 +53,64 @@ jobs:
           rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu
 
       - name: Create Python virtual environment
+        working-directory: ${{ github.workspace }}
         run: python3 -m venv venv
 
       - name: Clone Bittensor SDK repo
+        working-directory: ${{ github.workspace }}
         run: git clone https://github.com/opentensor/bittensor.git
 
       - name: Setup Bittensor SDK from cloned repo
-        working-directory: bittensor
+        working-directory: ${{ github.workspace }}/bittensor
         run: |
-          source ../venv/bin/activate
+          source ${{ github.workspace }}/venv/bin/activate
           git checkout staging
           python3 -m pip install --upgrade pip
           python3 -m pip install '.[dev]'
-          pip install maturin
+          python3 -m pip install maturin
 
       - name: Clone Bittensor Wallet repo
         run: git clone https://github.com/opentensor/btwallet.git
 
       - name: Checkout PR branch in Wallet repo
-        working-directory: btwallet
+        working-directory: ${{ github.workspace }}/btwallet
         run: |
           git fetch origin ${{ github.event.pull_request.head.ref }}
           git checkout ${{ github.event.pull_request.head.ref }}
           echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
 
       - name: Build and install Rust Bittensor Wallet package
-        working-directory: btwallet
+        working-directory: ${{ github.workspace }}
         run: |
-          source ../venv/bin/activate
+          source ${{ github.workspace }}/venv/bin/activate
           maturin develop
 
       - name: Clone Subtensor repo
+        working-directory: ${{ github.workspace }}
         run: git clone https://github.com/opentensor/subtensor.git
 
       - name: Checkout Subtensor repo to `devnet-ready` branch
         working-directory: subtensor
         run: git checkout devnet-ready
 
-      - name: Find e2e test files
-        working-directory: bittensor
-        id: find-tests
-        run: |
-          test_files=$(find tests/e2e_tests -name "test_*.py" | jq -R -s -c 'split("\n")[:-1]')
-          echo "TEST_FILES=$test_files" >> $GITHUB_ENV
-          echo "matrix=$(jq -n --argjson files "$test_files" '{include: [$files[] | {test_file: .}]}')" >> $GITHUB_ENV
-
-    outputs:
-      matrix: ${{ env.matrix }}
-
-  run-e2e-tests:
-    needs: run-tests
-    runs-on: ubuntu-latest
-    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.run-tests.outputs.matrix) }}
-    steps:
-      - name: Check-out repository
-        uses: actions/checkout@v4
-
-      - name: Restore Python virtual environment
-        uses: actions/download-artifact@v4
-        with:
-          name: python-venv
-          path: venv
-
       - name: Run Bittensor SDK e2e test - ${{ matrix.test_file }}
-        working-directory: bittensor
+        working-directory: ${{ github.workspace }}
         run: |
-          source ../venv/bin/activate
-          if [ -f "../subtensor/scripts/localnet.sh" ]; then
-            LOCALNET_SH_PATH="../subtensor/scripts/localnet.sh" \
-            python3 -m pytest ${{ matrix.test_file }} -s
+          source ${{ github.workspace }}/venv/bin/activate
+          LOCALNET_SH="${{ github.workspace }}/subtensor/scripts/localnet.sh"
+          
+          if [ -f "$LOCALNET_SH" ]; then
+            export LOCALNET_SH_PATH="$LOCALNET_SH"
+            
+            TESTS=$(find tests/e2e_tests -name "test_*.py" | tr '\n' ' ')
+            
+            if [ -z "$TESTS" ]; then
+              echo "No tests found in tests/e2e_tests/"
+              exit 1
+            fi
+            
+            python3 -m pytest $TESTS -s
           else
-            echo "Error: localnet.sh not found"
+            echo "Error: localnet.sh not found at $LOCALNET_SH"
             exit 1
           fi
